### ISSUE TITLE
Could you write down the license you are using for this project?

### ISSUE THREAD

**Issue by jichen3000** [javier2491/FaceQnet#11]
This project is awesome, I am using your project in my project.
But I notice you didn't mention the license for this project.
So could you write down the license you are using for this project?

**Comment by Huangdai** [comment]
Which version of  tensorflow

**Comment by javier-hernandezo** [comment]
FaceQnet is free of use for non-profit projects. If you wish to use it in your project, just please give us the proper recognition as authors, for example citing the FaceQnet ICB paper.

**Comment by RyanCV** [comment]
> FaceQnet is free of use for non-profit projects. If you wish to use it in your project, just please give us the proper recognition as authors, for example citing the FaceQnet ICB paper.

Is it  possible for commercial product?

**Comment by LOGANATHAN6432** [comment]
Is it possible for commercial product?
