### ISSUE TITLE
About ground truth generating

### ISSUE THREAD

**Issue by amyburden** [javier2491/FaceQnet#13]
I notice that you do score normalization in your paper. Can I ask about details about how you get the score normalization from l2 distance?

**Comment by javier-hernandezo** [comment]
Hello,

The test process is the next: 

1) We extracted face embeddings for each image.
2) We computed the Euclidean Distance between images. These distances represent the dissimilarity between the pair of images. 
3) The distances have been transformed to similarity scores s into the [0,1] range using the next equation:
                         _s = 1=(1 + e^d)_, 
being _d_ each mated distance with zero mean and unitary standard deviation (we use a small sample of images to estimate the mean and the std of the distances previously).

Regards.

**Comment by amyburden** [comment]
@uam-biometrics Thanks you so much for such inspiring work. Use the face recognition model as supervision information is really a great idea. So I believe the equation should be s = 1/(1+e^d), right?

**Comment by amyburden** [comment]
@uam-biometrics Is it possible for you to provide image id in vgg2 face you choose as high-quality images?

**Comment by javier-hernandezo** [comment]
> @uam-biometrics Thanks you so much for such inspiring work. Use the face recognition model as supervision information is really a great idea. So I believe the equation should be s = 1/(1+e^d), right?

Yes sorry, there was a mistake in my comment.  _s = 1/(1+e^d)_ is correct.

**Comment by javier-hernandezo** [comment]
> @uam-biometrics Is it possible for you to provide image id in vgg2 face you choose as high-quality images?

Hello, I don´t have the list of images used as gallery images, but I will prepare it and upload it to the repository soon.

**Comment by javier-hernandezo** [comment]
The high quality images used for training have been uploaded to src/VGGFace2_Templates.txt

Regards
