### ISSUE TITLE
ICAO Compliance Software

### ISSUE THREAD

**Issue by zhilide** [javier2491/FaceQnet#18]
Hi , I dont learn about ICAO Compliance Software,could you give me a download website about ICAO Compliance Software? thanks!

**Comment by javier-hernandezo** [comment]
Hello,

The ICAO compliance software is not of our property, so we can make it available in our website.
It has been developed by M. Ferrara, Annalisa Franco, Dario Maio, and Davide Maltoni in U. Bologna. You can try to contact them.
Another option is reading their associated publication "Face Image Conformance to ISO/ICAO Standards in
Machine Readable Travel Documents" where they give details about each individual test and how to implement them.

**Comment by zhilide** [comment]
> Hello,
> 
> The ICAO compliance software is not of our property, so we can make it available in our website.
> It has been developed by M. Ferrara, Annalisa Franco, Dario Maio, and Davide Maltoni in U. Bologna. You can try to contact them.
> Another option is reading their associated publication "Face Image Conformance to ISO/ICAO Standards in
> Machine Readable Travel Documents" where they give details about each individual test and how to implement them.

thanks!
