### ISSUE TITLE
The speed of inference

### ISSUE THREAD

**Issue by nerddd** [javier2491/FaceQnet#6]
Hi, I used the model you provided. But the inference takes a lot of time if I want to make it real-time in video. So I wonder if there is a light weigt model? Or could you please provide the dataset you collected? Thank you!

**Comment by javier-hernandezo** [comment]
Hello,

We do not have any light model, sorry. However, are you using a GPU for inference? That should speed it up. 
Regarding your second question, I do not know what are you referring to with the sentence "the dataset you collected". Do you mean the quality scores for the testing sets of VGGFace2 and Biosecure?  We are planning to upload the quality scores of the whole VGGFace2, BioSecure, CyberExtruder, and LFW databases.

Regards

**Comment by gabrielpcosta** [comment]
If possible, do you think you could share the code with the dataset for training the neural network too? I also wanted to test training this network in a  lightweight architecture.

**Comment by javier-hernandezo** [comment]
I am preparing the code for training and fine-tuning FaceQnet with other dataset. To get the training dataset you have to download VGGFace2 and take the 300 first users for training as I did: http://www.robots.ox.ac.uk/~vgg/data/vgg_face2/

Regards
