### ISSUE TITLE
Questions about the dataset/scores and training code

### ISSUE THREAD

**Issue by c9o** [javier2491/FaceQnet#7]
Hi @uam-biometrics ,
Your work is really interesting!
Do you plan to publish the face database with obtained quality score?
It would be very great if you can release the training code and the quality score generation code.
Regards

**Comment by javier-hernandezo** [comment]
Hello @c9o,
Thakn you very much for trying our code.
In our paper and experiments we used the VGGFace2 Database that isalready public for download (http://www.robots.ox.ac.uk/~vgg/data/vgg_face2/) and the BioSecure Database. This last database is not public already, sorry, but we are currently working on make it available online.

We are not making public the training and architecture of FaceQnet, but you can download the pretrained model and use it or fine-tune it with your own data.
For your information, the training data we used are the first 300 users of the VGGFace2 database. 

Regards,

Javier

**Comment by c9o** [comment]
@uam-biometrics 
Thanks for your reply.
Will you publish the quality scores?
Regards

**Comment by javier-hernandezo** [comment]
We are planning to upload the quality scores of the whole VGGFace2, BioSecure, CyberExtruder, and LFW databases in the near future.

Regards

**Comment by c9o** [comment]
That' great!

Thanks

**Comment by ChengSongyang** [comment]
> We are planning to upload the quality scores of the whole VGGFace2, BioSecure, CyberExtruder, and LFW databases in the near future.
> 
> Regards

Hello, I'd like to know if the quality scores of the whole VGGFace2, BioSecure, CyberExtruder, and LFW databases are uploaded?where can I get it? Thanks
