### ISSUE TITLE
How to use this model in tensorflow C++?

### ISSUE THREAD

**Issue by hipitt** [javier2491/FaceQnet#8]
**How to use this model in tensorflow C++?**

```
        std::vector<std::pair<std::string, tensorflow::Tensor>> inputs = {
                {"？？？",       image_batch},
        };

        std::vector<tensorflow::Tensor> outputs;
        tensorflow::Status status = session->Run(inputs, {"？？"}, {}, &outputs);
```

**Comment by javier-hernandezo** [comment]
Hello,

I recommend you to use frugally_deep for using keras pretrained models in C++: https://github.com/Dobiasd/frugally-deep

I have used it in the past and it works perfectly. 

Regards

**Comment by hipitt** [comment]
Would you please show me an example of frugal-deep ?

**Comment by javier-hernandezo** [comment]
Here you have a code example in which we are loading a model from .json file (this file can be created from a keras .h5 file):

#include <fdeep/fdeep.hpp>
int main()
{
    const auto model = fdeep::load_model("fdeep_model.json");
    const auto result = model.predict({
        fdeep::tensor5(fdeep::shape5(1, 1, 240, 320, 3), 42),
        fdeep::tensor5(fdeep::shape5(1, 1, 240, 320, 3), 43)
        });
    std::cout << fdeep::show_tensor5s(result) << std::endl;
}


The command to create the .json would be:

python3 keras_export/convert_model.py keras_model.h5 fdeep_model.json

However, in their Github there are a README file and a FAQ document with clear explanations and examples about the proper use of frugally_deep. 

https://github.com/Dobiasd/frugally-deep/blob/master/README.md
https://github.com/Dobiasd/frugally-deep/blob/master/FAQ.md

Regards
