### ISSUE TITLE
Question on example result

### ISSUE THREAD

**Issue by Garfield-kh** [javier2491/FaceQnet#9]
Thanks for the opensource. 
I have read the paper and tried on this code, it looks very magic.

One question want to ask~
I noticed that in example data:
For the female: the score looks quite good from sorted sequence.
However, for the male one, it shows that _Picture 29.png_ has the best score, while the others with better illumination condition such as _Picture 20.png_, _Picture 30.png_ has lower score compared with _Picture 29.png_.
Is this the different perspectives between human and machine?
Or it is due to the bias in the training data? Like maybe some gallery photo with best ICAO is quite different to the rest probes?

Thank you.

**Comment by javier-hernandezo** [comment]
Hello,

Yes, the FaceQnet model extracts a quality score related tothe expected performance o the matchers, not just  only  related to human quality. Very often these two are similar, but in some cases both approaches may differ.

Also we must have into account that the model is not perfect and its quality scores should be only treated as approximations.

Regards,

Javier
